// Mots vides français courants (articles, pronoms, prépositions,
// conjonctions, auxiliaires) — filtrés avant comptage de fréquence lexicale.
// Non exhaustif par construction : à enrichir au fil de l'usage plutôt que
// de viser l'exhaustivité dès le départ.
export const STOPWORDS_FR = new Set([
  'alors', 'ainsi', 'après', 'assez', 'aucun', 'aucune', 'aujourd', 'aupres',
  'auquel', 'aura', 'auront', 'aussi', 'autre', 'autres', 'aux', 'avaient',
  'avais', 'avait', 'avant', 'avec', 'avez', 'avoir', 'avons',
  'bien', 'bon',
  'car', 'ce', 'ceci', 'cela', 'celle', 'celles', 'celui', 'ces', 'cet',
  'cette', 'ceux', 'chaque', 'chez', 'comme', 'comment', 'contre',
  'dans', 'de', 'debout', 'dedans', 'dehors', 'dela', 'depuis', 'des',
  'deux', 'devant', 'devra', 'divers', 'doit', 'donc', 'dont', 'dos', 'droite',
  'du', 'duquel', 'durant',
  'elle', 'elles', 'en', 'encore', 'entre', 'envers', 'es', 'est', 'et',
  'etaient', 'etais', 'etait', 'etant', 'etc', 'ete', 'etre', 'eu', 'eux',
  'fait', 'faites', 'fois', 'font',
  'hors',
  'ici', 'il', 'ils',
  'jamais', 'je',
  'juste',
  'la', 'laquelle', 'le', 'lequel', 'les', 'lesquelles', 'lesquels', 'leur',
  'leurs', 'longtemps', 'lors', 'lui',
  'ma', 'maintenant', 'mais', 'mes', 'moi', 'moins', 'mon',
  'ne', 'ni', 'non', 'nos', 'notre', 'nous',
  'ont', 'ou', 'ouias', 'oui',
  'par', 'parce', 'parle', 'parlent', 'parler', 'parmi', 'pas', 'pendant',
  'personne', 'peu', 'peut', 'plupart', 'plus', 'plutot', 'pour', 'pourquoi',
  'pourrait', 'proche', 'pres', 'puis', 'puisque',
  'quand', 'que', 'quel', 'quelle', 'quelles', 'quels', 'qui', 'quoi',
  'quoique',
  'sa', 'sans', 'se', 'sein', 'sera', 'seront', 'ses', 'seulement', 'si',
  'sien', 'soi', 'soit', 'son', 'sont', 'sous', 'soyez', 'sur',
  'ta', 'tandis', 'tant', 'te', 'tellement', 'telle', 'tels', 'tes', 'toi',
  'ton', 'toujours', 'tous', 'tout', 'toute', 'toutes', 'tres', 'trop', 'tu',
  'une', 'unes', 'uns',
  'vers', 'via', 'voici', 'voila', 'vos', 'votre', 'vous',
])
